server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_security?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    password:

jwt:
  expire: 604800
  secret: lxyker

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl